const skillsData = {
  technical: [
    "Python",
    "C/C++/C#",
    "JavaScript/TypeScript",
    "Java",
    "React",
    "Next.js",
    "Node.js",
    "RISC-V Assembly",
    "ARM Assembly",
    "Bare Metal Programming",
    "Embedded Systems",
    "PCB Design",
    "Signal Analysis",
    "MATLAB",
    "OpenCV",
    "ROS",
    "Machine Learning",
    "Git",
    "Swift",
    "Soldering & Circuit Prototyping",
  ],
  platforms: [
    "Linux",
    "Fusion 360",
    "SolidWorks",
    "EasyEDA",
    "KiCad",
    "Figma",
    "Jupyter Notebook",
    "IntelliJ IDEA",
    "VS Code",
    "XCode",
    "GitHub",
    "Notion",
    "Trello",
    "AWS",
    "Vivado",
    "STM32CubeIDE",
    "PlatformIO",
    "Microcontrollers (Arduino, STM32, ESP32, RPi Pico)",
  ],
};

export default skillsData;